[".config/nvim"]
  type = "archive"
  # url = "https://github.com/NvChad/NvChad.git"
  url = "https://github.com/NvChad/NvChad/archive/refs/heads/v2.0.tar.gz"
  exact = true
  stripComponents = 1
  # [".config/nvim".clone]
  #   args = ["--depth=1"]
