[".config/nvim"]
  type = "archive"
  url = "https://github.com/NvChad/NvChad/archive/refs/heads/v2.0.tar.gz"
  exact = true
  stripComponents = 1

[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm.git"
