#!/usr/bin/env zsh 

ZSH_PATH="$HOME/.zsh"
CONFIG_PATH="$ZSH_PATH/config.zsh"
ALIASES_PATH="$ZSH_PATH/aliases.zsh"
ANTIGEN_PATH="$ZSH_PATH/antigen.zsh"  # antigen.sharats.me
NVM_DIR="$HOME/.nvm"
HISTFILE="$HOME/.zsh_history"
EDITOR="nvim"
HISTSIZE=10000
SAVEHIST=10000

setopt appendhistory
(cat $HOME/.cache/wal/sequences &)


source $CONFIG_PATH
source $ANTIGEN_PATH

if [ ! -f $ANTIGEN_PATH ]; then  # Is Antigen installed?
    echo "Antigen is not found!" >&2
		
	curl -L git.io/antigen > $ANTIGEN_PATH  # If no, then install it
fi

antigen use oh-my-zsh

packages=(
  reobin/typewritten@main  # Docs on typewritten.dev
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-autosuggestions
  git web-search colored-man-pages
  adb aliases command-not-found
  pip z 
)

for package in ${packages[@]}; do 
  antigen bundle $package 
done
antigen apply


source $ALIASES_PATH

bindkey "^[[Z" autosuggest-accept  # shift+tab
