#!/usr/bin/env bash


# Init vars
export bspwm="$HOME/.config/bspwm"
export os="$HOME/.config/os"
export PATH="${os}/scripts:${PATH}"
export TERM="kitty"
export TERMINAL="kitty"
export EDITOR="nvim"
export VISUAL="nvim"
export QT_QPA_PLATFORMTHEME=gtk3                
export TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1
export BROWSER="firefox"


bspc monitor -d "1" "2" "3" "4" "5" "6"
bspc config border_width 1
bspc config top_padding 28
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 0
bspc config split_ratio 0.5
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_motion_interval 16
bspc config pointer_action1 move

# Init apps
killall sxhkd dunst polybar greenclip syncthinga http-server
sxhkd -c ${bspwm}/sxhkdrc &
polybar -q default &
dunst &
greenclip daemon &
syncthing &  # web interface http://localhost:8384
# Required `npm install http-server -g`
# Available on http://127.0.0.1:8080
# In browser use extension "new tab override"
http-server $HOME/.config/chevron/ &


# Init cmds
xkbcomp $HOME/.config/xkb/config $DISPLAY
xsetroot -cursor_name left_ptr
xset r rate 170 40
synclient PalmDetect=1 HorizEdgeScroll=1 TapButton1=1 TapButton2=3 TapButton3=2 MaxSpeed=2
xset s 0 0; xset dpms 0 0 0; xset -dpms
numlockx
xdg-settings set default-web-browser firefox.desktop


# Set random wall and generate color scheme
${os}/scripts/set-wall.sh
source $HOME/.cache/wal/colors.sh


# Setting bspwm
bspc config normal_border_color $background
bspc config active_border_color $color2
bspc config focused_border_color $color2
bspc config presel_feedback_color $background


# Setting apps
bspc rule --add Zathura state=tiled


# Notify done
notify-send "bspwm" "System done"
