#!/usr/bin/env bash


# Init vars
export bspwm="$HOME/.config/bspwm"
export os="$HOME/.config/os"
export PATH="$os/scripts:$PATH"
export TERM="kitty"
export TERMINAL="kitty"
export EDITOR="nvim"
export QT_QPA_PLATFORMTHEME=gtk3                
export TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1
export BROWSER="firefox"


# Build color scheme
${os}/scripts/color-scheme-builder.sh


# Import color vars
source ${bspwm}/colors.sh


# Setting bspwm
bspc config normal_border_color $bg
bspc config active_border_color $slate3
bspc config focused_border_color $slate3
bspc config presel_feedback_color $bg

bspc monitor -d "1" "2" "3" "4" "5" "6"
bspc config border_width 1
bspc config top_padding 28
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 0
bspc config split_ratio 0.5
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod3
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_motion_interval 16


# Init apps
killall sxhkd dunst polybar greenclip syncthing
sxhkd -c ${bspwm}/sxhkdrc &
polybar -q default &
dunst &
greenclip daemon &
syncthing &  # web interface http://localhost:8384


# Init cmds
setxkbmap -option caps:escape
setxkbmap -layout us,ru -option grp:win_space_toggle
xsetroot -cursor_name left_ptr
xset r rate 170 40
synclient PalmDetect=1 HorizEdgeScroll=1 TapButton1=1 TapButton2=3 TapButton3=2 MaxSpeed=2
xset s 0 0; xset dpms 0 0 0; xset -dpms
numlockx
xdg-settings set default-web-browser firefox.desktop


# Random wall
wallPath=$(shuf -en1 ${os}/walls/*)
feh --no-fehbg --bg-fill ${wallPath}


# Notify done
notify-send "bspwm" "System done"
