#!/usr/bin/env bash


# Init vars
export PATH="$HOME/.local/bin:${PATH}"
export LCACHE="$HOME/.cache"
export LBIN="$HOME/.local/bin"
export LSTATE="$HOME/.local/state"
export LSHARE="$HOME/.local/share"
export LCONFIG="$HOME/.config"
export LCHEZMOI="$HOME/.local/share/chezmoi"
export LBSPWM="$HOME/.config/bspwm"
export QT_QPA_PLATFORMTHEME=gtk3                
export TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1
export BROWSER="firefox"
export TERM="kitty"
export TERMINAL="kitty"
export EDITOR="nvim"
export VISUAL="nvim"
export SHELL="/usr/bin/zsh"

# Set color scheme and random wallpaper
l-settheme --only-set &> /dev/null

# Init apps
l-initapps &> /dev/null

# Init cmds
l-initcmds &> /dev/null

# Setting bspwm
l-configurebspwm &> /dev/null

# Notify done
notify-send "bspwm" "System done"
