#!/usr/bin/env bash


# Init vars
export PATH="$HOME/.local/bin:${PATH}"
export LCACHE="$HOME/.cache"
export LBIN="$HOME/.local/bin"
export LSTATE="$HOME/.local/state"
export LSHARE="$HOME/.local/share"
export LCONFIG="$HOME/.config"
export LCHEZMOI="$HOME/.local/share/chezmoi"
export LBSPWM="$HOME/.config/bspwm"
export TERM="kitty"
export TERMINAL="kitty"
export EDITOR="nvim"
export VISUAL="nvim"
export QT_QPA_PLATFORMTHEME=gtk3                
export TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1
export BROWSER="firefox"

# Init apps
l-initapps

# Init cmds
l-initcmds

# Set random wall and generate color scheme
l-setwall

# Setting bspwm
l-configurebspwm

# Notify done
notify-send "bspwm" "System done"
